name: GitHub Actions Lint
on:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/**"

concurrency:
  group: publish-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: reviewdog / actionlint
        uses: reviewdog/action-actionlint@v1
        with:
          fail_on_error: true
