name: Lint
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - ".github/**"

concurrency:
  group: lint-${{ github.event.pull_request.number || github.sha }}

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  ktlint:
    name: Check Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: reviewdog / ktlint
        uses: ScaCap/action-ktlint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          ktlint_version: 1.2.1
